import type Database from 'better-sqlite3';
import { type BetterSQLite3Database } from 'drizzle-orm/better-sqlite3';
import {
	services, industries, teamMembers,
	caseStudies, insights, partners, careers, resources, testimonials, clientLogos, devices
} from './schema';

export function seed(db: BetterSQLite3Database, sqlite: Database.Database) {
	// Guard: skip if already seeded
	const row = sqlite.prepare('SELECT COUNT(*) as count FROM services').get() as { count: number };
	if (row.count > 0) return;

	// ══════════════════════════════════════════════════════════════════════════════
	// SERVICES (12)
	// ══════════════════════════════════════════════════════════════════════════════
	db.insert(services).values([
		{ title:'IT Consulting & System Integration', slug:'it-consulting', category:'core',
			description:'Strategic technology consulting and seamless system integration across enterprise environments.',
			longDescription:'We architect and implement comprehensive IT solutions aligned with your business objectives. From infrastructure modernization to cloud migration, our consultants deliver integrated systems that drive operational excellence.',
			icon:'network',
			features: JSON.stringify(['Enterprise Architecture Design','Cloud Migration & Multi-Cloud Strategy','Legacy System Modernization','API Integration & Middleware','IT Infrastructure Assessment','Digital Transformation Roadmap']),
			techStack: JSON.stringify(['AWS','Azure','GCP','Kubernetes','Terraform','SAP','Oracle']),
			engagementModels: JSON.stringify(['Fixed-Price Project','Time & Materials','Retainer']),
			sortOrder:1 },
		{ title:'IoT & Advanced Device Implementation', slug:'iot-devices', category:'core',
			description:'End-to-end IoT deployment and advanced device integration for industrial and commercial applications.',
			longDescription:'From sensor networks in mining to medical device integrations in hospitals, we design, deploy, and manage IoT ecosystems that transform raw data into actionable intelligence.',
			icon:'cpu',
			features: JSON.stringify(['Industrial IoT Sensor Networks','Edge Computing & Gateway Management','Real-time Monitoring Dashboards','Predictive Maintenance Systems','SCADA & PLC Integration','Medical Device Connectivity']),
			techStack: JSON.stringify(['AWS IoT Core','Azure IoT Hub','MQTT','LoRaWAN','NB-IoT','Node-RED','InfluxDB']),
			engagementModels: JSON.stringify(['Fixed-Price Project','Managed Service','Time & Materials']),
			sortOrder:2 },
		{ title:'IT Recruitment & Outsourcing', slug:'recruitment', category:'staffing',
			description:'Expert IT talent acquisition and managed outsourcing services for technology teams.',
			longDescription:'Access top-tier IT professionals through our specialized recruitment and outsourcing services.',
			icon:'users',
			features: JSON.stringify(['Permanent Placement & Executive Search','Contract & Temporary Staffing','Dedicated Development Teams','Staff Augmentation','Technical Skill Assessment','Onboarding & Retention Support']),
			techStack: JSON.stringify(['ATS Platform','Skills Matrix Tool','Background Screening','Psychometric Testing']),
			engagementModels: JSON.stringify(['Retained Search','Contingency Placement','Managed Team','Staff Augmentation']),
			sortOrder:3 },
		{ title:'Technology Device Rental & Sales', slug:'device-rental', category:'core',
			description:'Flexible technology hardware procurement, rental programs, and lifecycle management.',
			longDescription:'Get enterprise-grade hardware with flexible acquisition options. Full lifecycle management including deployment, maintenance, and secure disposal.',
			icon:'monitor',
			features: JSON.stringify(['Enterprise Hardware Procurement','Short & Long-term Device Rental','Device Lifecycle Management','Asset Tracking & Inventory','Maintenance & Support Plans','Secure Data Wiping & Disposal']),
			techStack: JSON.stringify(['Cisco','HP Enterprise','Dell','Lenovo','Zebra Technologies','Raspberry Pi','Arduino']),
			engagementModels: JSON.stringify(['Outright Purchase','Operating Lease','Financial Lease','Rental']),
			sortOrder:4 },
		{ title:'Managed Services (MSP)', slug:'managed-services', category:'managed',
			description:'24/7 monitoring, helpdesk, incident handling, and SLA-backed support operations.',
			longDescription:'Offload your IT operations to our expert managed services team. Round-the-clock monitoring, proactive incident resolution, and SLA-guaranteed uptime.',
			icon:'shield',
			features: JSON.stringify(['Service Desk & Helpdesk (L1/L2/L3)','24/7 Infrastructure Monitoring','Patch Management & Updates','Incident & Change Management','Monthly Reporting & SLA Reviews','Escalation Management']),
			techStack: JSON.stringify(['ServiceNow','Zabbix','Grafana','PagerDuty','Ansible','Prometheus']),
			engagementModels: JSON.stringify(['Monthly Retainer','Per-Device Pricing','Custom SLA']),
			sortOrder:5 },
		{ title:'Cybersecurity Services', slug:'cybersecurity', category:'managed',
			description:'Risk assessments, vulnerability management, SOC-aligned operations, and endpoint hardening.',
			longDescription:'Protect your critical assets with multi-layered cybersecurity services including comprehensive risk assessments, penetration testing, and 24/7 SOC monitoring.',
			icon:'lock',
			features: JSON.stringify(['Security Risk Assessment & Audit','Penetration Testing & Vulnerability Scanning','SOC Monitoring & Incident Response','Endpoint Security & MDM','SIEM Integration & Log Management','Compliance Readiness (ISO 27001, PCI-DSS)']),
			techStack: JSON.stringify(['Palo Alto','CrowdStrike','Splunk','Fortinet','Qualys','Tenable','Microsoft Sentinel']),
			engagementModels: JSON.stringify(['Project-Based Assessment','Managed SOC Retainer','Time & Materials']),
			sortOrder:6 },
		{ title:'Cloud & DevOps', slug:'cloud-devops', category:'core',
			description:'Cloud migration, CI/CD pipelines, IaC, and performance + cost optimization.',
			longDescription:'Accelerate your software delivery with cloud-native architectures, automated deployment pipelines, and Infrastructure-as-Code practices.',
			icon:'cloud',
			features: JSON.stringify(['Cloud Migration & Lift-and-Shift','CI/CD Pipeline Design & Implementation','Infrastructure as Code (Terraform, Ansible)','Container Orchestration (Kubernetes)','Cost Optimization & FinOps','Observability & Monitoring Stack']),
			techStack: JSON.stringify(['AWS','Azure','GCP','Terraform','Kubernetes','Docker','GitLab CI','GitHub Actions','Datadog']),
			engagementModels: JSON.stringify(['Fixed-Price Migration','Time & Materials','Managed Cloud Ops']),
			sortOrder:7 },
		{ title:'Data & AI Enablement', slug:'data-ai', category:'consulting',
			description:'Modern BI, data pipelines, and practical AI assistants for operations and teams.',
			longDescription:'Turn your data into a strategic asset. We build modern data platforms, AI-powered analytics, and intelligent automation solutions.',
			icon:'chart',
			features: JSON.stringify(['Data Warehouse & Lakehouse Architecture','ETL/ELT Pipeline Engineering','Business Intelligence & Dashboards','Machine Learning Model Development','AI Workflow Automation','Real-time Analytics & Streaming']),
			techStack: JSON.stringify(['Snowflake','dbt','Apache Spark','Power BI','Tableau','Python','TensorFlow','OpenAI API']),
			engagementModels: JSON.stringify(['Discovery Sprint','Fixed-Price Project','Managed Analytics']),
			sortOrder:8 },
		{ title:'IT Asset Management (ITAM + MDM)', slug:'itam-mdm', category:'managed',
			description:'Asset lifecycle visibility, policy enforcement, and endpoint compliance controls.',
			longDescription:'Gain complete visibility over your technology assets. Track every device from procurement to disposal, enforce security policies, and ensure compliance.',
			icon:'database',
			features: JSON.stringify(['Hardware & Software Asset Inventory','Mobile Device Management (MDM)','License Compliance & Optimization','Remote Configuration & Policy Enforcement','Access Control & Zero-Trust Enforcement','Audit-Ready Reporting']),
			techStack: JSON.stringify(['Microsoft Intune','Jamf','ManageEngine','ServiceNow ITAM','Ivanti','Snipe-IT']),
			engagementModels: JSON.stringify(['Per-Device Monthly','Fixed Implementation + Retainer']),
			sortOrder:9 },
		{ title:'Business Continuity & Disaster Recovery', slug:'bcdr', category:'consulting',
			description:'Backup strategy, DR architecture, recovery runbooks, and resilience testing.',
			longDescription:'Ensure your business survives any disruption with comprehensive BCDR strategies, defined RPO/RTO targets, and regular drill exercises.',
			icon:'refresh',
			features: JSON.stringify(['Business Impact Analysis (BIA)','Backup Architecture & Automation','Disaster Recovery Site Design','RPO/RTO Definition & Validation','Failover Drill & Tabletop Exercises','Recovery Runbook Documentation']),
			techStack: JSON.stringify(['Veeam','Zerto','AWS Backup','Azure Site Recovery','Commvault','Veritas']),
			engagementModels: JSON.stringify(['Fixed-Price Assessment','Implementation Project','Managed DR Retainer']),
			sortOrder:10 },
		{ title:'Training & Change Management', slug:'training', category:'consulting',
			description:'Structured onboarding and role-based enablement to ensure post-launch adoption.',
			longDescription:'Technology only delivers value when people use it effectively. We provide structured training programs and change management frameworks.',
			icon:'book',
			features: JSON.stringify(['Role-Based Training Curriculum Design','Change Readiness Assessment','Communications Planning','Train-the-Trainer Programs','Post-Launch Adoption Campaigns','User Feedback & Iteration']),
			techStack: JSON.stringify(['LMS Platforms','Microsoft Viva','Miro','Confluence','Jira','Survey Tools']),
			engagementModels: JSON.stringify(['Per-Engagement Project','Retainer for Ongoing Programs']),
			sortOrder:11 },
		{ title:'Technology Procurement Advisory', slug:'procurement', category:'consulting',
			description:'Vendor-neutral guidance for architecture, sourcing, and commercial decision quality.',
			longDescription:'Navigate the complex vendor landscape with confidence. Vendor-neutral advisors help you evaluate solutions objectively and negotiate contracts.',
			icon:'briefcase',
			features: JSON.stringify(['Vendor Landscape Analysis','RFP/RFQ Development & Management','Solution Evaluation & Scoring','TCO & ROI Analysis','Contract Negotiation Support','Implementation Partner Selection']),
			techStack: JSON.stringify(['Gartner Research','Forrester','Vendor Demo Platforms','Cost Modeling Tools']),
			engagementModels: JSON.stringify(['Fixed-Price Advisory','Hourly Consulting','Project-Based']),
			sortOrder:12 }
	]).run();

	// ══════════════════════════════════════════════════════════════════════════════
	// INDUSTRIES (8)
	// ══════════════════════════════════════════════════════════════════════════════
	db.insert(industries).values([
		{ name:'Mining & Resources', slug:'mining',
			description:'Rugged IoT solutions and integrated systems for mining operations, exploration, and resource management.',
			longDescription:'The mining industry demands technology that performs in the harshest environments. We deploy ruggedized IoT sensor networks for environmental monitoring, equipment tracking, and safety systems.',
			solutions: JSON.stringify(['Environmental Monitoring Systems','Equipment Tracking & Fleet Management','Underground Communication Networks','Safety & Compliance Automation','Predictive Maintenance for Heavy Machinery','Geological Data Integration']),
			metrics: JSON.stringify([{value:'41%',label:'Downtime Reduction'},{value:'99.7%',label:'Sensor Network Uptime'},{value:'500+',label:'Devices Deployed'}]),
			sortOrder:1 },
		{ name:'Financial Services', slug:'financial-services',
			description:'Secure, compliant technology solutions for banking, insurance, and fintech organizations.',
			longDescription:'Financial institutions require technology partners who understand regulatory requirements and security imperatives. We deliver core banking integrations and regulatory compliance platforms.',
			solutions: JSON.stringify(['Core Banking System Integration','Payment Gateway & POS Systems','Regulatory Compliance Platforms','Fraud Detection & Security Systems','Digital Banking Solutions','Data Center Infrastructure']),
			metrics: JSON.stringify([{value:'99.99%',label:'Transaction Uptime'},{value:'<50ms',label:'Processing Latency'},{value:'ISO 27001',label:'Security Standard'}]),
			sortOrder:2 },
		{ name:'Healthcare & Medical', slug:'healthcare',
			description:'Medical device integration, hospital information systems, and healthcare IoT for modern facilities.',
			longDescription:'Healthcare technology must be reliable, interoperable, and compliant with strict medical regulations. We integrate medical devices with hospital information systems.',
			solutions: JSON.stringify(['Medical Device Integration (HL7/FHIR)','Hospital Information System (HIS)','Patient Monitoring Networks','Telehealth & Remote Care Platforms','Medical Equipment Procurement','Healthcare Data Analytics']),
			metrics: JSON.stringify([{value:'HL7/FHIR',label:'Compliance Standard'},{value:'3x',label:'Faster Data Access'},{value:'200+',label:'Medical Devices Connected'}]),
			sortOrder:3 },
		{ name:'Manufacturing', slug:'manufacturing',
			description:'Smart factory solutions with industrial IoT, automation, and production optimization systems.',
			longDescription:'Transform your manufacturing operations with Industry 4.0 solutions including automated production lines, quality control sensors, and digital twin simulations.',
			solutions: JSON.stringify(['Smart Factory Automation','Production Line Monitoring','Quality Control IoT Sensors','Supply Chain Visibility','Digital Twin Simulation','Energy Management Systems']),
			metrics: JSON.stringify([{value:'25%',label:'OEE Improvement'},{value:'60%',label:'Defect Reduction'},{value:'Real-time',label:'Production Visibility'}]),
			sortOrder:4 },
		{ name:'Smart City & Government', slug:'smart-city',
			description:'Connected infrastructure solutions for urban management, public services, and citizen engagement.',
			longDescription:'We help government agencies build smarter, more responsive urban environments with traffic management IoT, utility SCADA, and public safety networks.',
			solutions: JSON.stringify(['Traffic Management & Smart Signals','Utility SCADA & Smart Metering','Public Safety Monitoring Systems','Smart Parking & Mobility','Environmental Sensing Networks','Citizen Service Digital Platforms']),
			metrics: JSON.stringify([{value:'30%',label:'Congestion Reduction'},{value:'20%',label:'Energy Savings'},{value:'15+',label:'City Projects'}]),
			sortOrder:5 },
		{ name:'Energy & Utilities', slug:'energy',
			description:'Power grid monitoring, renewable energy IoT, pipeline telemetry, and SCADA integration.',
			longDescription:'The energy sector requires ultra-reliable systems. We design SCADA systems, remote monitoring networks, and predictive analytics that optimize energy generation and distribution.',
			solutions: JSON.stringify(['Power Grid Monitoring & SCADA','Renewable Energy IoT (Solar/Wind)','Pipeline Telemetry & Leak Detection','Smart Metering Infrastructure (AMI)','Energy Analytics & Forecasting','Substation Automation']),
			metrics: JSON.stringify([{value:'15%',label:'Energy Loss Reduction'},{value:'99.9%',label:'SCADA Availability'},{value:'2,000+',label:'Smart Meters Deployed'}]),
			sortOrder:6 },
		{ name:'Logistics & Supply Chain', slug:'logistics',
			description:'Fleet tracking, cold chain monitoring, warehouse automation, and supply chain visibility platforms.',
			longDescription:'Modern logistics demands end-to-end visibility. We implement fleet tracking, cold chain IoT monitoring, and warehouse automation across your entire operation.',
			solutions: JSON.stringify(['GPS Fleet Tracking & Telematics','Cold Chain IoT Monitoring','Warehouse Management Systems (WMS)','RFID Asset Tracking','Last-Mile Delivery Optimization','Supply Chain Analytics Dashboard']),
			metrics: JSON.stringify([{value:'20%',label:'Delivery Cost Reduction'},{value:'98%',label:'Cold Chain Compliance'},{value:'Real-time',label:'Fleet Visibility'}]),
			sortOrder:7 },
		{ name:'Telecommunications', slug:'telecommunications',
			description:'Network infrastructure, OSS/BSS integration, and next-generation connectivity solutions.',
			longDescription:'We support telecom operators with network management systems, OSS/BSS integrations, and IoT connectivity platforms spanning 4G/5G and beyond.',
			solutions: JSON.stringify(['Network Management Systems (NMS)','OSS/BSS Platform Integration','IoT Connectivity Management','5G Infrastructure Planning','Subscriber Management Systems','Network Performance Analytics']),
			metrics: JSON.stringify([{value:'<99ms',label:'Network Latency'},{value:'1M+',label:'IoT Endpoints Managed'},{value:'5',label:'Major Operators Served'}]),
			sortOrder:8 }
	]).run();

	// ══════════════════════════════════════════════════════════════════════════════
	// CASE STUDIES (6)
	// ══════════════════════════════════════════════════════════════════════════════
	db.insert(caseStudies).values([
		{ title:"Underground Sensor Network for Indonesia's Largest Coal Producer",
			slug:'coal-mining-iot-network', client:"Leading Indonesian Coal Producer",
			industry:'Mining & Resources', industrySlug:'mining', serviceSlug:'iot-devices',
			challenge:"The client had zero real-time visibility into equipment health, air quality, or worker location across 4 underground mines. Unplanned equipment failures caused 3-4 days of downtime per month, costing millions in lost production.",
			solution:"We designed and deployed a ruggedized LoRaWAN mesh network across 12km of tunnels. 340 wireless sensors monitor air quality (CO, CH4, O2), vibration on critical machinery, and worker locations via RFID. Edge computing aggregates data before forwarding to a Grafana dashboard with automated WhatsApp alerts.",
			results:"Within 6 months, unplanned downtime dropped 41%. The early-warning vibration system flagged 3 imminent conveyor belt failures before they occurred, preventing Rp 4.2 billion in costs. Air quality alerts reduced worker health incidents by 67%.",
			metrics: JSON.stringify([{value:'41%',label:'Downtime Reduction',icon:'trending-down'},{value:'Rp 4.2B',label:'Cost Savings',icon:'dollar'},{value:'340',label:'Sensors Deployed',icon:'cpu'},{value:'67%',label:'Safety Incidents Reduced',icon:'shield'}]),
			technologies: JSON.stringify(['LoRaWAN','MQTT','InfluxDB','Grafana','AWS IoT Core','Node-RED','Raspberry Pi Industrial']),
			testimonialQuote:"The real-time visibility Asiateknologi delivered underground has fundamentally changed how we operate. Our safety record improved dramatically.",
			testimonialAuthor:'Hendra Kusuma', testimonialTitle:'VP of Operations',
			coverGradient:'from-amber-900/40 to-dark-950', featured:1, sortOrder:1 },
		{ title:'Core Banking Integration for Regional Cooperative Bank',
			slug:'bank-core-integration', client:'BPR Nusantara Digital',
			industry:'Financial Services', industrySlug:'financial-services', serviceSlug:'it-consulting',
			challenge:"The bank operated on a legacy core banking system from 2004 incompatible with modern payment networks and OJK regulatory reporting. Manual reconciliation consumed 15+ hours weekly.",
			solution:"We built a middleware integration layer using RESTful APIs and ISO 8583 translation to bridge the legacy core to BI-FAST, GPN, and SNAP. A real-time OJK reporting module and mobile banking frontend were delivered without replacing the core system.",
			results:"The bank launched mobile banking within 6 months, onboarding 12,000 new digital customers in Q1. Reconciliation dropped from 15 hours to 45 minutes. OJK reporting became fully automated with zero errors.",
			metrics: JSON.stringify([{value:'12,000',label:'New Digital Customers',icon:'users'},{value:'95%',label:'Reconciliation Time Saved',icon:'clock'},{value:'0',label:'Regulatory Errors',icon:'shield'},{value:'6mo',label:'Time to Launch',icon:'calendar'}]),
			technologies: JSON.stringify(['ISO 8583','REST API','BI-FAST','SNAP','Java Spring Boot','PostgreSQL','Redis']),
			testimonialQuote:"Asiateknologi let us compete with digital banks without ripping out our core system. ROI exceeded projections.",
			testimonialAuthor:'Ir. Suryadi Hartono', testimonialTitle:'Director, Technology & Operations',
			coverGradient:'from-blue-900/40 to-dark-950', featured:1, sortOrder:2 },
		{ title:'Patient Monitoring Network Across 8-Hospital Group',
			slug:'hospital-patient-monitoring', client:'Regional Hospital Group',
			industry:'Healthcare & Medical', industrySlug:'healthcare', serviceSlug:'iot-devices',
			challenge:"The hospital group needed centralized monitoring of ICU patients across 8 hospitals. Medical devices from 6 manufacturers used incompatible protocols. Nurses spent 30% of their shift manually transcribing device readings.",
			solution:"We deployed an HL7/FHIR R4 integration engine normalizing data from all 6 device manufacturers. A central dashboard provides real-time vitals for all patients. Critical-value alerts reach nursing smartphones within 8 seconds of threshold breach.",
			results:"Nursing admin time reduced 31%. Critical alerts now reach staff under 10 seconds vs. the previous 4-minute average. The HIS now contains continuous vitals streams instead of manual spot-check entries.",
			metrics: JSON.stringify([{value:'31%',label:'Nursing Time Saved',icon:'clock'},{value:'<10s',label:'Alert Response Time',icon:'zap'},{value:'200+',label:'Medical Devices Connected',icon:'activity'},{value:'8',label:'Hospitals Integrated',icon:'building'}]),
			technologies: JSON.stringify(['HL7 FHIR R4','Mirth Connect','PostgreSQL','WebSocket','React','Node.js','Docker']),
			testimonialQuote:"Our nurses now spend time with patients, not paperwork. The unified monitoring view has improved our ability to catch critical changes early.",
			testimonialAuthor:'dr. Ratna Dewi, Sp.An', testimonialTitle:'Medical Director, ICU Services',
			coverGradient:'from-emerald-900/40 to-dark-950', featured:1, sortOrder:3 },
		{ title:'Smart Factory Rollout for Automotive Parts Manufacturer',
			slug:'smart-factory-automotive', client:'PT Dharma Precision Parts',
			industry:'Manufacturing', industrySlug:'manufacturing', serviceSlug:'iot-devices',
			challenge:"Production lines ran at 62% OEE with frequent unplanned stops. Quality issues were only discovered at end-of-line inspection, causing 8.5% scrap rate.",
			solution:"We installed 180 vibration and temperature sensors on CNC machines. ML models predict tooling replacement 4-6 hours in advance. Inline quality sensors detect dimensional deviations and trigger automatic machine parameter adjustments.",
			results:"OEE improved from 62% to 81% in 9 months. Scrap rate dropped to 2.1%. Annual savings: Rp 6.8 billion.",
			metrics: JSON.stringify([{value:'81%',label:'OEE (from 62%)',icon:'trending-up'},{value:'2.1%',label:'Scrap Rate (from 8.5%)',icon:'trending-down'},{value:'94%',label:'Predictive Accuracy',icon:'cpu'},{value:'Rp 6.8B',label:'Annual Savings',icon:'dollar'}]),
			technologies: JSON.stringify(['OPC-UA','InfluxDB','Python ML','Grafana','MQTT','TensorFlow Lite']),
			coverGradient:'from-indigo-900/40 to-dark-950', featured:0, sortOrder:4 },
		{ title:'Cold Chain & Fleet IoT for National Pharmaceutical Distributor',
			slug:'cold-chain-fleet-iot', client:'PT Sumber Mas Distribusi',
			industry:'Logistics & Supply Chain', industrySlug:'logistics', serviceSlug:'iot-devices',
			challenge:"85 refrigerated trucks distributed pharmaceutical products with unreliable manual temperature logging. Cold chain breaches discovered only at delivery, after spoilage. Fuel costs escalating.",
			solution:"GPS + temperature + door-sensor IoT units in all 85 vehicles connected via 4G. Real-time WhatsApp alerts for cold chain breaches. AI-powered route optimization. Pharma clients access immutable temperature logs per shipment.",
			results:"Cold chain breaches reduced 89%. Fuel costs decreased 14%. Won 3 new national pharma distribution contracts.",
			metrics: JSON.stringify([{value:'89%',label:'Breach Reduction',icon:'thermometer'},{value:'14%',label:'Fuel Cost Savings',icon:'trending-down'},{value:'85',label:'Vehicles Connected',icon:'truck'},{value:'3',label:'New Contracts Won',icon:'star'}]),
			technologies: JSON.stringify(['4G IoT','GPS Tracking','AWS IoT','WhatsApp Business API','Python','PostgreSQL']),
			coverGradient:'from-cyan-900/40 to-dark-950', featured:0, sortOrder:5 },
		{ title:'City-Wide Adaptive Traffic Management, Surabaya',
			slug:'surabaya-traffic-management', client:'Dinas Perhubungan Kota Surabaya',
			industry:'Smart City & Government', industrySlug:'smart-city', serviceSlug:'iot-devices',
			challenge:"Fixed signal timing optimized for 2015 patterns caused chronic congestion at 240 intersections. Emergency vehicle response averaged 18 minutes.",
			solution:"Computer vision cameras at 240 intersections. Real-time vehicle density AI adjusts signal timing every 30 seconds. Emergency vehicle preemption clears green corridors within 2 minutes of dispatch.",
			results:"Average wait time reduced 28%. Emergency response improved from 18 to 11 minutes. Estimated city-wide fuel savings: Rp 2.1 trillion annually.",
			metrics: JSON.stringify([{value:'28%',label:'Congestion Reduction',icon:'trending-down'},{value:'11min',label:'Emergency Response (from 18)',icon:'zap'},{value:'240',label:'Intersections Managed',icon:'map'},{value:'Real-time',label:'Traffic Adaptation',icon:'activity'}]),
			technologies: JSON.stringify(['Computer Vision','YOLOv8','Adaptive Signal Control','Fiber Optic','AWS','Python','React']),
			coverGradient:'from-purple-900/40 to-dark-950', featured:0, sortOrder:6 }
	]).run();

	// ══════════════════════════════════════════════════════════════════════════════
	// INSIGHTS (6)
	// ══════════════════════════════════════════════════════════════════════════════
	db.insert(insights).values([
		{ title:'Why LoRaWAN is the Backbone of Industrial IoT in Southeast Asia',
			slug:'lorawan-industrial-iot-southeast-asia',
			excerpt:"Long-range, low-power connectivity is transforming how industries monitor assets across challenging environments — from underground mines to remote plantations.",
			content:`## The Connectivity Challenge in Harsh Environments\n\nIndustrial IoT deployments in Southeast Asia face a unique challenge: the environments where data is most valuable — underground mines, remote plantations, offshore platforms — are exactly where traditional connectivity fails.\n\nWi-Fi doesn't reach. Cellular is expensive at scale. LoRaWAN solves both problems.\n\n## What Makes LoRaWAN Different\n\n- **Range**: 2–15km in open terrain, 500m–2km underground\n- **Battery life**: Sensors run 5–10 years on AA batteries\n- **Cost**: $15–$50 per node vs $200+ for cellular\n- **Penetration**: Signals penetrate concrete and soil far better than 2.4GHz\n\n## Real Deployments\n\nIn our mining deployment, we achieved reliable sensor coverage across 12km of underground tunnels using 8 gateway nodes. Air quality, equipment vibration, and worker location data streams reliably at 30-second intervals.\n\n## When LoRaWAN Isn't the Answer\n\nLoRaWAN is not designed for high-bandwidth or low-latency applications. If you need video streaming, sub-100ms latency, or high data throughput — use 4G/5G or fiber instead.\n\n## Building Your LoRaWAN Strategy\n\nStart with a coverage survey. Understand your environment's RF characteristics before committing to gateway placement. The ROI case for LoRaWAN in industrial SEA deployments is compelling — payback periods of 8–14 months are typical.`,
			author:'Budi Santoso', authorRole:'Head of IoT Solutions',
			category:'IoT', tags: JSON.stringify(['LoRaWAN','Industrial IoT','Mining','Connectivity']),
			readTime:7, coverGradient:'from-cyan-900 to-dark-950', sortOrder:1 },
		{ title:'HL7 FHIR R4: The Standard Every Healthcare CTO Needs to Understand',
			slug:'hl7-fhir-r4-healthcare-guide',
			excerpt:"Healthcare interoperability is no longer optional. Here's what HL7 FHIR R4 means for your hospital's technology strategy.",
			content:`## The Interoperability Problem\n\nIndonesia's healthcare system runs on dozens of incompatible HIS, medical device, and laboratory systems. Nurses transcribe data manually, physicians make decisions with incomplete information.\n\n## What HL7 FHIR R4 Actually Is\n\nFHIR (Fast Healthcare Interoperability Resources) R4 is the latest healthcare data exchange standard. Think of it as the HTTP of healthcare — a universal language any compliant system can speak.\n\nKey concepts:\n- **Resources**: Standardized data objects (Patient, Observation, Medication, Encounter)\n- **RESTful API**: Standard CRUD operations via HTTP\n- **SMART on FHIR**: OAuth 2.0 authorization layer\n\n## Why R4 Matters\n\nIf you're procuring any new medical system in 2025+, FHIR R4 compliance should be a **hard requirement** in your RFP. Non-compliant systems create integration debt that costs 3–10x the initial savings.\n\n## The ROI Case\n\nIn our hospital group deployment, HL7 FHIR integration reduced nursing documentation time by 31% and eliminated manual data entry errors.`,
			author:'Sarah Chen', authorRole:'Chief Technology Officer',
			category:'Healthcare Tech', tags: JSON.stringify(['HL7','FHIR','Healthcare','Interoperability']),
			readTime:9, coverGradient:'from-emerald-900 to-dark-950', sortOrder:2 },
		{ title:"The Hidden Cost of Reactive IT: Why Indonesian Enterprises Are Switching to MSP",
			slug:'managed-services-vs-reactive-it',
			excerpt:"Most mid-market companies underestimate their true IT operations cost by 40–60%. Here's how to calculate your real cost.",
			content:`## The Break-Fix Illusion\n\nMany Indonesian enterprises believe they're saving money by managing IT reactively. The math tells a different story.\n\n## Calculating Your True IT Cost\n\n1. **Staff time**: 20 people × 2 hours/month of IT issues = Rp 38.4M/year in hidden loss\n2. **Downtime**: A 4-hour server outage = Rp 200–500M in lost productivity\n3. **Emergency premiums**: Break-fix vendors charge 2–3x for urgent calls\n4. **Security risk**: Average SEA data breach cost = $2.87M (IBM 2024)\n\n## The MSP Value Proposition\n\nA well-structured MSP typically runs Rp 15–45M/month for a 50-person company. Proactive monitoring catches 73% of incidents before they cause downtime.\n\n## When MSP Makes Sense\n\n- 0–2 IT staff for 50+ employees\n- 2+ major IT incidents in the past 12 months\n- No 24/7 coverage capability internally\n- Regulatory compliance requires documented change management`,
			author:'Yudi Michael', authorRole:'Chief Executive Officer',
			category:'IT Strategy', tags: JSON.stringify(['Managed Services','MSP','Cost Optimization']),
			readTime:8, coverGradient:'from-violet-900 to-dark-950', sortOrder:3 },
		{ title:'SCADA Modernization: From Legacy PLCs to Cloud-Connected Control',
			slug:'scada-modernization-guide',
			excerpt:"Most Indonesian industrial facilities run SCADA systems from the 1990s. Here's how to modernize without shutting down production.",
			content:`## The Aging SCADA Problem\n\nWalk into most Indonesian manufacturing plants and you'll find SCADA systems on Windows XP, communicating via RS-485 serial — security vulnerabilities and data islands.\n\n## Why You Can't Just Replace Everything\n\nA steel plant's PLC network cannot go offline for a migration project. **Modernization must be non-disruptive.**\n\n## The Three-Layer Approach\n\n**Layer 1: Data Collection (Months 1-3)**\nInstall OPC-UA gateways alongside existing PLCs. Read Modbus/DNP3 without interfering with control logic.\n\n**Layer 2: Visibility (Months 3-6)**\nBuild a modern SCADA dashboard (Ignition, Grafana) reading from the new data layer. Operators gain modern visualization while legacy remains in control.\n\n**Layer 3: Integration (Months 6-18)**\nConnect operational data to ERP and predictive analytics. Migrate control logic on non-critical systems first.\n\n## The Business Case\n\nModernization projects show ROI through 15–25% OEE improvement and predictive maintenance savings. Payback periods of 18–30 months are typical in Indonesia.`,
			author:'Budi Santoso', authorRole:'Head of IoT Solutions',
			category:'Industry 4.0', tags: JSON.stringify(['SCADA','PLC','Industrial IoT','Manufacturing']),
			readTime:10, coverGradient:'from-amber-900 to-dark-950', sortOrder:4 },
		{ title:"Indonesia's IT Talent Market 2025: What Hiring Managers Need to Know",
			slug:'indonesia-it-talent-market-2025',
			excerpt:"Demand for specialized IT roles grew 34% in 2024. Here's what's driving the gap and how companies are adapting.",
			content:`## The Supply-Demand Gap\n\nIndonesia produces ~200,000 IT graduates per year. Industry needs ~600,000 IT professionals. The gap is real — and not evenly distributed.\n\n## The Hardest Roles to Fill (2025)\n\nBased on our 200+ placements in 2024:\n1. **Cloud Architects**: 4–6 month fill time\n2. **Industrial IoT Engineers**: 3–5 months\n3. **Cybersecurity Analysts**: 3–4 months\n4. **Data Engineers**: 2–3 months\n5. **DevOps/SRE**: 2–3 months\n\n## Compensation Benchmarks (Jakarta, 2025)\n\n- Junior Developer: Rp 8–15M/month\n- Mid-level Developer: Rp 15–30M/month\n- Senior Engineer: Rp 30–60M/month\n- Cloud Architect: Rp 45–90M/month\n\n## What Works in 2025\n\n- Hybrid/remote flexibility as standard\n- Learning budgets (certifications, conferences)\n- Hiring process under 3 weeks\n- Staff augmentation for niche roles`,
			author:'Diana Putri', authorRole:'Director of Recruitment',
			category:'IT Talent', tags: JSON.stringify(['Recruitment','IT Talent','Indonesia','Salaries']),
			readTime:7, coverGradient:'from-blue-900 to-dark-950', sortOrder:5 },
		{ title:'Building a Disaster Recovery Plan That Actually Works',
			slug:'disaster-recovery-plan-checklist',
			excerpt:"Most DR plans fail when tested because they were written, not practiced. Here's a battle-tested framework.",
			content:`## The DR Plan Problem\n\nEvery company has a DR plan. Few have tested it under realistic conditions. In our BCDR assessments, 68% of DR plans have critical gaps preventing recovery within stated RTO targets.\n\n## Define Recovery Targets First\n\n**RTO** (How long can this system be down?):\n- Core banking: 15 minutes\n- E-commerce: 2 hours\n- HR system: 24 hours\n\n**RPO** (How much data can you afford to lose?):\n- Transaction systems: 0 (real-time replication)\n- Customer databases: 1 hour\n- Analytics: 24 hours\n\n## Five Failure Modes We See Most Often\n\n1. **Backup that can't restore** — never been tested\n2. **Documentation out of date** — references decommissioned servers\n3. **Dependencies not mapped** — authentication service has 6hr RTO blocking 2hr app RTO\n4. **DR site too similar to production** — same data center doesn't protect against facility failure\n5. **Staff who've never done it** — first runbook execution is during actual incident\n\n## Recommended Testing Cadence\n\n- Monthly: Backup restoration test\n- Quarterly: Component failover test\n- Semi-annually: Full DR drill\n- Annually: Tabletop exercise with all stakeholders`,
			author:'Sarah Chen', authorRole:'Chief Technology Officer',
			category:'Cybersecurity', tags: JSON.stringify(['Disaster Recovery','BCDR','Business Continuity','RTO','RPO']),
			readTime:9, coverGradient:'from-red-900 to-dark-950', sortOrder:6 }
	]).run();

	// ══════════════════════════════════════════════════════════════════════════════
	// PARTNERS (9)
	// ══════════════════════════════════════════════════════════════════════════════
	db.insert(partners).values([
		{ name:'Amazon Web Services', partnerType:'technology', tier:'advanced', description:'AWS Advanced Partner. Certified expertise in cloud migration, IoT Core, and managed services.', url:'https://aws.amazon.com', sortOrder:1 },
		{ name:'Microsoft Azure', partnerType:'technology', tier:'gold', description:'Microsoft Gold Partner. Azure IoT Hub, Cloud, and Microsoft 365 enterprise deployments.', url:'https://azure.microsoft.com', sortOrder:2 },
		{ name:'Cisco Systems', partnerType:'technology', tier:'premier', description:'Cisco Premier Partner. Networking, cybersecurity, and industrial IoT connectivity.', url:'https://cisco.com', sortOrder:3 },
		{ name:'Siemens Digital Industries', partnerType:'technology', tier:'certified', description:'Siemens Technology Partner for industrial automation, SCADA, and smart infrastructure.', url:'https://siemens.com', sortOrder:4 },
		{ name:'Palo Alto Networks', partnerType:'technology', tier:'authorized', description:'Palo Alto Authorized Partner for next-generation firewall and zero-trust security.', url:'https://paloaltonetworks.com', sortOrder:5 },
		{ name:'Snowflake', partnerType:'technology', tier:'select', description:'Snowflake Select Partner for cloud data warehousing implementations.', url:'https://snowflake.com', sortOrder:6 },
		{ name:'BytePlus', partnerType:'technology', tier:'authorized', description:'BytePlus Partner for AI-powered cloud services, CDN, and real-time data solutions.', url:'https://byteplus.com', sortOrder:7 },
		{ name:'Vonage', partnerType:'technology', tier:'select', description:'Vonage API Partner for CPaaS, SMS, voice, and video communication integrations.', url:'https://vonage.com', sortOrder:8 },
		{ name:'Ruijie Networks', partnerType:'technology', tier:'certified', description:'Ruijie Certified Partner for enterprise networking, Wi-Fi, and campus infrastructure.', url:'https://ruijienetworks.com', sortOrder:9 },
		{ name:'Alibaba Cloud', partnerType:'technology', tier:'advanced', description:'Alibaba Cloud Advanced Partner for cloud computing, ECS, OSS, and AI services in Asia.', url:'https://alibabacloud.com', sortOrder:10 },
		{ name:'Huawei', partnerType:'technology', tier:'gold', description:'Huawei Gold Partner for enterprise networking, cloud, and smart city infrastructure.', url:'https://huawei.com', sortOrder:11 },
		{ name:'Tencent Cloud', partnerType:'technology', tier:'select', description:'Tencent Cloud Partner for cloud hosting, CDN, gaming infrastructure, and AI services.', url:'https://intl.cloud.tencent.com', sortOrder:12 },
		{ name:'Confluent', partnerType:'technology', tier:'select', description:'Confluent Partner for Apache Kafka-based event streaming, real-time data pipelines, and stream processing.', url:'https://confluent.io', sortOrder:13 },
		{ name:'Tableau', partnerType:'technology', tier:'authorized', description:'Tableau (Salesforce) Partner for enterprise business intelligence, interactive dashboards, and data visualization.', url:'https://tableau.com', sortOrder:14 },
		{ name:'Databricks', partnerType:'technology', tier:'select', description:'Databricks Partner for lakehouse architecture, Apache Spark, Delta Lake, and unified data & AI platforms.', url:'https://databricks.com', sortOrder:15 },
		{ name:'Power BI', partnerType:'technology', tier:'gold', description:'Microsoft Power BI Partner for self-service analytics, interactive reports, and enterprise data visualization.', url:'https://powerbi.microsoft.com', sortOrder:16 },
		{ name:'Looker', partnerType:'technology', tier:'select', description:'Google Looker Partner for modern business intelligence, embedded analytics, and data-driven application development.', url:'https://looker.com', sortOrder:17 },
		{ name:'Microsoft Fabric', partnerType:'technology', tier:'advanced', description:'Microsoft Fabric Partner for end-to-end analytics, data engineering, data science, and real-time intelligence.', url:'https://microsoft.com/fabric', sortOrder:18 },
		{ name:'Odoo', partnerType:'technology', tier:'certified', description:'Odoo Certified Partner for ERP, CRM, accounting, inventory, and open-source business application suites.', url:'https://odoo.com', sortOrder:19 },
		{ name:'ISO 27001', partnerType:'certification', description:'Information Security Management System certification.', sortOrder:20 },
		{ name:'ISO 9001:2015', partnerType:'certification', description:'Quality Management System certification.', sortOrder:21 },
		{ name:'Kominfo Registered', partnerType:'certification', description:"Registered Electronic System Organizer (PSE) with Indonesia's Ministry of Communication and Information Technology.", sortOrder:22 }
	]).run();

	// ══════════════════════════════════════════════════════════════════════════════
	// CAREERS (8)
	// ══════════════════════════════════════════════════════════════════════════════
	db.insert(careers).values([
		{ title:'Senior IoT Solutions Engineer', slug:'senior-iot-solutions-engineer', department:'IoT Engineering', location:'Jakarta, Indonesia', type:'Full-time', experience:'4-7 years',
			description:"Lead design and deployment of industrial IoT sensor networks for mining, manufacturing, and utilities clients. Own technical architecture from LoRaWAN gateway placement to cloud data pipeline design.",
			requirements: JSON.stringify(['4+ years IoT system design experience','Hands-on with LoRaWAN, MQTT, or NB-IoT','Python and/or Node.js proficiency','AWS IoT Core or Azure IoT Hub experience','Industrial automation understanding preferred','Fluent in Bahasa Indonesia and English']),
			niceToHave: JSON.stringify(['Mining or utilities environment experience','AWS IoT or Azure IoT certification','InfluxDB and Grafana experience','Embedded systems background']),
			benefits: JSON.stringify(['Competitive salary + performance bonus','Health insurance (BPJS + private)','Certification budget Rp 5M/year','Flexible/remote arrangement','Project laptop & equipment']), isActive:1 },
		{ title:'Cloud & DevOps Engineer', slug:'cloud-devops-engineer', department:'Cloud Engineering', location:'Jakarta / Remote', type:'Full-time', experience:'3-5 years',
			description:"Design and manage cloud infrastructure for clients and internal platforms. Implement CI/CD pipelines, containerization, and IaC across AWS and Azure.",
			requirements: JSON.stringify(['3+ years cloud infrastructure (AWS or Azure)','Strong Terraform and/or Ansible','Kubernetes administration','CI/CD pipeline implementation','Linux administration','Monitoring stacks (Prometheus, Grafana, Datadog)']),
			niceToHave: JSON.stringify(['AWS Solutions Architect or Azure Administrator cert','FinOps / cloud cost optimization experience','DevSecOps background']),
			benefits: JSON.stringify(['Salary Rp 20-40M/month','Health insurance','AWS/Azure certification fully sponsored','Remote-first with quarterly gatherings','Home office equipment budget']), isActive:1 },
		{ title:'Cybersecurity Analyst (SOC)', slug:'cybersecurity-analyst-soc', department:'Cybersecurity', location:'Jakarta, Indonesia', type:'Full-time', experience:'2-4 years',
			description:"Monitor, detect, and respond to security threats across managed client environments in our Security Operations Center.",
			requirements: JSON.stringify(['2+ years SOC or incident response','SIEM platform proficiency (Splunk, Sentinel)','MITRE ATT&CK framework knowledge','Network traffic analysis (Wireshark)','CompTIA Security+ preferred','Shift flexibility for 24/7 coverage']),
			niceToHave: JSON.stringify(['CEH or OSCP certification','EDR platform experience (CrowdStrike, SentinelOne)','Malware analysis fundamentals','Python or PowerShell scripting']),
			benefits: JSON.stringify(['Shift allowance','Premium health insurance','Security certification budget','Career path to Senior Analyst → Threat Hunter → SOC Lead']), isActive:1 },
		{ title:'IT Recruitment Consultant', slug:'it-recruitment-consultant', department:'Recruitment & Staffing', location:'Jakarta, Indonesia', type:'Full-time', experience:'2-5 years',
			description:"Manage end-to-end recruitment for IT professional placements across software engineering, cloud, data, and IoT roles.",
			requirements: JSON.stringify(['2+ years IT recruitment experience','Strong tech stack understanding','LinkedIn Recruiter and Boolean search proficiency','ATS platform experience','Excellent communication in Bahasa Indonesia and English','Target-oriented with placement track record']),
			niceToHave: JSON.stringify(['Software development background','Jakarta tech community network','IoT/industrial technology recruitment experience']),
			benefits: JSON.stringify(['Base salary + uncapped placement commission','Health insurance','Annual team outing','Flexible hours']), isActive:1 },
		{ title:'Data Engineer', slug:'data-engineer', department:'Data & AI', location:'Jakarta / Remote', type:'Full-time', experience:'3-5 years',
			description:"Build and maintain data pipelines, warehouses, and analytics infrastructure for enterprise clients.",
			requirements: JSON.stringify(['3+ years data engineering','Strong SQL and Python','Modern data stack (dbt, Airflow)','Cloud data warehouse (Snowflake, BigQuery, Redshift)','Data modeling knowledge','Real-time pipeline experience']),
			niceToHave: JSON.stringify(['Apache Spark experience','dbt Certified Developer','IoT time-series data (InfluxDB, TimescaleDB)','Kafka or Kinesis experience']),
			benefits: JSON.stringify(['Remote-first','Salary Rp 25-50M/month','Conference & training budget','Diverse industry data challenges']), isActive:1 },
		{ title:'System Integration Consultant', slug:'system-integration-consultant', department:'IT Consulting', location:'Jakarta, Indonesia', type:'Full-time', experience:'4-8 years',
			description:"Lead enterprise system integration projects for banking, healthcare, and manufacturing clients.",
			requirements: JSON.stringify(['4+ years IT consulting or system integration','API design and middleware (MuleSoft, WSO2)','Enterprise application knowledge (SAP, Oracle, Dynamics)','Strong project management','C-level stakeholder experience','Business English fluency']),
			niceToHave: JSON.stringify(['Healthcare integration (HL7/FHIR)','Financial systems knowledge','PMP or PRINCE2 certification','MuleSoft Certified Developer']),
			benefits: JSON.stringify(['Salary Rp 30-65M/month','SEA travel opportunities','Certification sponsorship','Fast-track to Principal Consultant']), isActive:1 },
		{ title:'Business Development Manager – Enterprise', slug:'business-development-manager', department:'Sales & Business Development', location:'Jakarta, Indonesia', type:'Full-time', experience:'5-10 years',
			description:"Drive enterprise account acquisition across mining, financial services, healthcare, and manufacturing verticals.",
			requirements: JSON.stringify(['5+ years enterprise technology sales','Rp 500M+ deal track record','IT consulting/MSP value proposition understanding','Strong Jakarta business network','6–12 month sales cycle management','Executive presentation skills']),
			niceToHave: JSON.stringify(['IoT/industrial technology sales','Mining or banking sector relationships','MBA or technical degree','Regional SEA experience']),
			benefits: JSON.stringify(['Competitive base + aggressive commission','Car allowance','Premium health insurance','Executive training programs']), isActive:1 },
		{ title:'Junior IoT Hardware Technician', slug:'junior-iot-hardware-technician', department:'IoT Engineering', location:'Jakarta / Field-based', type:'Full-time', experience:'0-2 years',
			description:"Support IoT hardware deployment and field maintenance for sensor network projects. Ideal for fresh graduates wanting hands-on industrial IoT experience.",
			requirements: JSON.stringify(['Diploma/S1 Electronics or Electrical Engineering','Basic electronics and circuit troubleshooting','Willingness to travel to project sites','Physical fitness for field work','Valid SIM A driving license']),
			niceToHave: JSON.stringify(['Arduino or Raspberry Pi project experience','Basic networking knowledge','Electronics technician certification']),
			benefits: JSON.stringify(['Entry-level salary with structured career path','Field allowances','Health insurance (BPJS)','Senior IoT engineer mentorship','Training & certification program']), isActive:1 }
	]).run();

	// ══════════════════════════════════════════════════════════════════════════════
	// RESOURCES (6)
	// ══════════════════════════════════════════════════════════════════════════════
	db.insert(resources).values([
		{ title:'Industrial IoT Deployment Playbook for SEA Operations', slug:'industrial-iot-deployment-playbook', type:'whitepaper', description:"Comprehensive guide to planning, deploying, and maintaining industrial IoT sensor networks in challenging SEA environments.", industry:'Manufacturing', pages:28, gated:1, coverGradient:'from-cyan-800 to-dark-900', sortOrder:1 },
		{ title:'HL7 FHIR R4 Integration Guide for Indonesian Hospitals', slug:'hl7-fhir-r4-integration-guide', type:'guide', description:"Step-by-step guidance on implementing HL7 FHIR R4 compliant medical device integration for Indonesian healthcare facilities.", industry:'Healthcare', pages:22, gated:1, coverGradient:'from-emerald-800 to-dark-900', sortOrder:2 },
		{ title:'IT Talent Market Report: Indonesia 2025', slug:'it-talent-market-report-2025', type:'whitepaper', description:"Analysis of the Indonesian IT talent market including salary benchmarks, demand trends, and hiring strategy recommendations.", pages:18, gated:1, coverGradient:'from-blue-800 to-dark-900', sortOrder:3 },
		{ title:'BCDR Readiness Assessment Checklist', slug:'bcdr-readiness-assessment-checklist', type:'guide', description:"A practical 50-point checklist to evaluate your Business Continuity and Disaster Recovery readiness.", pages:12, gated:0, coverGradient:'from-red-800 to-dark-900', sortOrder:4 },
		{ title:'Cloud Migration Cost Estimation Framework', slug:'cloud-migration-cost-estimation', type:'datasheet', description:"Templates and methodology for estimating cloud migration costs with comparison models for AWS, Azure, and GCP.", pages:8, gated:0, coverGradient:'from-violet-800 to-dark-900', sortOrder:5 },
		{ title:'Mining IoT Safety Systems: Technical Specification Guide', slug:'mining-iot-safety-systems-spec', type:'datasheet', description:"Technical specifications for IoT-based worker safety and emergency communication systems in underground mining.", industry:'Mining', pages:14, gated:1, coverGradient:'from-amber-800 to-dark-900', sortOrder:6 }
	]).run();

	// ══════════════════════════════════════════════════════════════════════════════
	// TESTIMONIALS (6)
	// ══════════════════════════════════════════════════════════════════════════════
	db.insert(testimonials).values([
		{ quote:"The real-time visibility Asiateknologi delivered underground has fundamentally changed how we operate. Safety improved dramatically and maintenance now prevents failures instead of reacting to them.", authorName:'Hendra Kusuma', authorTitle:'VP of Operations', authorCompany:'Leading Coal Producer, Kalimantan', industry:'Mining', serviceSlug:'iot-devices', rating:5, sortOrder:1 },
		{ quote:"Asiateknologi let us compete with digital banks without replacing our core system. ROI exceeded projections.", authorName:'Ir. Suryadi Hartono', authorTitle:'Director of Technology & Operations', authorCompany:'BPR Nusantara Digital', industry:'Financial Services', serviceSlug:'it-consulting', rating:5, sortOrder:2 },
		{ quote:"Our nurses now spend time with patients, not paperwork. The unified monitoring view has improved our ability to catch critical changes early.", authorName:'dr. Ratna Dewi, Sp.An', authorTitle:'Medical Director, ICU Services', authorCompany:'Regional Hospital Group', industry:'Healthcare', serviceSlug:'iot-devices', rating:5, sortOrder:3 },
		{ quote:"We went from reactive to predictive manufacturing in under a year. OEE improvement alone paid back the entire project investment in 8 months.", authorName:'Hendro Wibowo', authorTitle:'Plant Manager', authorCompany:'PT Dharma Precision Parts', industry:'Manufacturing', serviceSlug:'iot-devices', rating:5, sortOrder:4 },
		{ quote:"Finding senior IoT engineers is nearly impossible. Asiateknologi placed 4 qualified candidates in 6 weeks. Their technical screening saved us 3 months of wasted interviews.", authorName:'Andi Prasetyo', authorTitle:'CTO', authorCompany:'AgriTech Startup, Jakarta', industry:'Technology', serviceSlug:'recruitment', rating:5, sortOrder:5 },
		{ quote:"Since moving to their managed services model, IT incidents dropped 70% and we haven't had a single unplanned outage in 14 months.", authorName:'Dewi Kusumawati', authorTitle:'Operations Director', authorCompany:'National Distribution Company', industry:'Logistics', serviceSlug:'managed-services', rating:5, sortOrder:6 }
	]).run();

	// ══════════════════════════════════════════════════════════════════════════════
	// CLIENT LOGOS (8)
	// ══════════════════════════════════════════════════════════════════════════════
	db.insert(clientLogos).values([
		{ name:'Top-5 Coal Producer', logoAlt:'Leading Coal Producer', industry:'Mining', sortOrder:1 },
		{ name:'BPR Nusantara Digital', logoAlt:'Regional Cooperative Bank', industry:'Financial Services', sortOrder:2 },
		{ name:'Regional Hospital Group', logoAlt:'8-Hospital Group', industry:'Healthcare', sortOrder:3 },
		{ name:'PT Dharma Precision', logoAlt:'Automotive Parts Manufacturer', industry:'Manufacturing', sortOrder:4 },
		{ name:'PT Sumber Mas Distribusi', logoAlt:'National Distributor', industry:'Logistics', sortOrder:5 },
		{ name:'Dinas Perhubungan Surabaya', logoAlt:'City Government', industry:'Smart City', sortOrder:6 },
		{ name:'National Pharma Company', logoAlt:'Pharmaceutical Company', industry:'Healthcare', sortOrder:7 },
		{ name:'AgriTech Innovators', logoAlt:'AgriTech Startup', industry:'Agriculture', sortOrder:8 }
	]).run();

	// ══════════════════════════════════════════════════════════════════════════════
	// TEAM MEMBERS (6)
	// ══════════════════════════════════════════════════════════════════════════════
	db.insert(teamMembers).values([
		{ name:'Yudi Michael', role:'Chief Executive Officer', bio:'Over 20 years in IT consulting across Southeast Asia. Yudi founded Asiateknologi with a vision to bridge the technology gap in emerging industries.', linkedinUrl:'#', sortOrder:1 },
		{ name:'Sarah Chen', role:'Chief Technology Officer', bio:'Former lead architect at a Fortune 500 tech company. Sarah drives our technical strategy with deep expertise in cloud-native architectures and large-scale IoT systems.', linkedinUrl:'#', sortOrder:2 },
		{ name:'Budi Santoso', role:'Head of IoT Solutions', bio:'Specialist in industrial IoT with extensive experience deploying sensor networks in mining and manufacturing. Budi leads our advanced device implementation team.', linkedinUrl:'#', sortOrder:3 },
		{ name:'Diana Putri', role:'Director of Recruitment', bio:'Built our recruitment division into a trusted source of IT professionals across Southeast Asia. Specializes in hard-to-fill technical roles.', linkedinUrl:'#', sortOrder:4 },
		{ name:'Michael Tan', role:'Head of Device Solutions', bio:'Expert in enterprise hardware lifecycle management with partnerships across major technology vendors.', linkedinUrl:'#', sortOrder:5 },
		{ name:'Rina Wijaya', role:'Head of Financial Services', bio:'Certified in financial technology and banking systems. Deep understanding of regulatory compliance for Indonesian financial institutions.', linkedinUrl:'#', sortOrder:6 }
	]).run();

	// ══════════════════════════════════════════════════════════════════════════════
	// DEVICES (9)
	// ══════════════════════════════════════════════════════════════════════════════
	db.insert(devices).values([
		{ name:'Enterprise Firewall Bundle Kit', slug:'firewall-bundle-kit', category:'network',
			description:'Managed firewall, VPN, IDS/IPS, and DDoS protection for enterprise networks. 1Gbps throughput, 500+ concurrent VPN sessions.',
			specs: JSON.stringify({type:'Appliance', throughput:'1Gbps', vpnSessions:'500+', ports:'8x 1GbE', power:'150W', size:'2U'}),
			features: JSON.stringify(['Next-Gen Firewall','VPN/IPSec','IDS/IPS Inspection','DDoS Protection','Advanced Threat Detection','Redundancy Support']),
			buyPrice:'950,000,000',
			rentPriceMonthly:'15,000,000',
			rentPricDaily:'600,000',
			availability:'in-stock',
			stockQuantity:5,
			coverGradient:'from-blue-900 to-dark-950',
			sortOrder:1, isActive:1 },
		{ name:'Workstation Pro 14"', slug:'workstation-pro-14', category:'laptop',
			description:'Professional mobile workstation for content creation, 3D modeling, and data science. Core Ultra 7, 32GB RAM, RTX 5880 Ada GPU.',
			specs: JSON.stringify({cpu:'Intel Core Ultra 7', ram:'32GB LPDDR5X', storage:'1TB NVMe SSD', gpu:'NVIDIA RTX 5880 Ada', display:'14" 4K OLED', weight:'1.8kg'}),
			features: JSON.stringify(['Professional GPU','4K OLED Display','Thunderbolt 4','32GB RAM','ISV Certified','Battery 14hrs']),
			buyPrice:'35,000,000',
			rentPriceMonthly:'1,800,000',
			rentPricDaily:'75,000',
			availability:'in-stock',
			stockQuantity:12,
			coverGradient:'from-indigo-900 to-dark-950',
			sortOrder:2, isActive:1 },
		{ name:'Developer MacBook Pro 16"', slug:'developer-macbook-pro-16', category:'laptop',
			description:'Apple M4 Max chip, ideal for full-stack developers, designers, and data scientists. 36GB unified memory, 1TB SSD.',
			specs: JSON.stringify({cpu:'Apple M4 Max', ram:'36GB', storage:'1TB SSD', gpu:'12-core GPU', display:'16" Liquid Retina XDR', battery:'22 hours'}),
			features: JSON.stringify(['M4 Max Chip','36GB RAM','Liquid Retina XDR','Thunderbolt 5','ProMotion 120Hz','Touch ID']),
			buyPrice:'42,000,000',
			rentPriceMonthly:'2,200,000',
			rentPricDaily:'90,000',
			availability:'in-stock',
			stockQuantity:8,
			coverGradient:'from-slate-900 to-dark-950',
			sortOrder:3, isActive:1 },
		{ name:'Business Ultrabook', slug:'business-ultrabook', category:'laptop',
			description:'Lightweight business laptop for corporate users. Intel Core i7, 16GB RAM, 512GB SSD, business security.',
			specs: JSON.stringify({cpu:'Intel Core i7-14700K', ram:'16GB DDR5', storage:'512GB NVMe', display:'15.6" FHD IPS', weight:'1.45kg', battery:'12hrs'}),
			features: JSON.stringify(['FHD Display','16GB RAM','Intel Iris Xe','WiFi 7','Fingerprint','BIOS Lock']),
			buyPrice:'18,000,000',
			rentPriceMonthly:'950,000',
			rentPricDaily:'40,000',
			availability:'in-stock',
			stockQuantity:20,
			coverGradient:'from-cyan-900 to-dark-950',
			sortOrder:4, isActive:1 },
		{ name:'Creator Tower X', slug:'creator-tower-x', category:'desktop',
			description:'High-performance desktop for creative professionals. AMD Ryzen 9, RTX 4090, 64GB RAM, liquid cooling.',
			specs: JSON.stringify({cpu:'AMD Ryzen 9 9950X', ram:'64GB DDR5', storage:'2TB NVMe RAID', gpu:'RTX 4090 24GB', cooling:'360mm AIO', power:'1000W'}),
			features: JSON.stringify(['RTX 4090 GPU','64GB RAM','Dual M.2 RAID','Liquid Cooling','WiFi 7','Thunderbolt 4']),
			buyPrice:'180,000,000',
			rentPriceMonthly:'8,500,000',
			rentPricDaily:'350,000',
			availability:'in-stock',
			stockQuantity:4,
			coverGradient:'from-purple-900 to-dark-950',
			sortOrder:5, isActive:1 },
		{ name:'Office PC Standard', slug:'office-pc-standard', category:'desktop',
			description:'Reliable office desktop for productivity work. Intel Core i5, 16GB RAM, integrated graphics.',
			specs: JSON.stringify({cpu:'Intel Core i5-13400F', ram:'16GB DDR4', storage:'512GB SSD', gpu:'Intel UHD 730', ports:'4x USB3.1', power:'250W'}),
			features: JSON.stringify(['Core i5 Processor','16GB RAM','512GB SSD','Integrated Graphics','Office Ready','Compact Form']),
			buyPrice:'8,500,000',
			rentPriceMonthly:'550,000',
			rentPricDaily:'25,000',
			availability:'in-stock',
			stockQuantity:25,
			coverGradient:'from-emerald-900 to-dark-950',
			sortOrder:6, isActive:1 },
		{ name:'Rack Server 2U Enterprise', slug:'rack-server-2u', category:'server',
			description:'Dual-socket enterprise server for virtualization and database workloads. Supports 32+ cores, 1TB+ RAM.',
			specs: JSON.stringify({cpu:'2x Intel Xeon Platinum 8590+', ram:'1TB DDR5', storage:'20x 1.92TB NVMe', network:'4x 25GbE', power:'5000W redundant'}),
			features: JSON.stringify(['Dual Xeon','1TB RAM Capable','NVMe RAID','Out-of-band IPMI','Redundant PSU','H-Security Support']),
			buyPrice:'650,000,000',
			rentPriceMonthly:'28,000,000',
			rentPricDaily:'1,200,000',
			availability:'custom-quote',
			stockQuantity:0,
			coverGradient:'from-red-900 to-dark-950',
			sortOrder:7, isActive:1 },
		{ name:'Event Ops Bundle - 20 Seats', slug:'event-ops-bundle-20', category:'bundle',
			description:'Complete event production package: 20x laptops, projector, audio setup, WiFi mesh, support engineer.',
			specs: JSON.stringify({laptops:'20x Developer Ultrabooks', projector:'4K Laser', audio:'Dolby Atmos', wifi:'WiFi 6E Mesh', support:'24/7 Tech Support'}),
			features: JSON.stringify(['20 Laptops Included','4K Projector','Wireless Audio','WiFi Mesh Network','Event Support Staff','Equipment Insurance']),
			buyPrice:'null',
			rentPriceMonthly:'null',
			rentPricDaily:'12,000,000',
			availability:'custom-quote',
			stockQuantity:0,
			coverGradient:'from-amber-900 to-dark-950',
			sortOrder:8, isActive:1 },
		{ name:'Smart Office Starter - 10 Seats', slug:'smart-office-starter-10', category:'bundle',
			description:'Complete office setup for small teams: 10x office PCs, office network, managed services, 12-month support.',
			specs: JSON.stringify({computers:'10x Office PC Standard', network:'Managed Firewall', modem:'5G Industrial', support:'12 months MSP', backup:'Daily Automated'}),
			features: JSON.stringify(['10 Computers','Network Managed','5G Connectivity','24/7 MSP Support','Automated Backup','Phishing Protection']),
			buyPrice:'120,000,000',
			rentPriceMonthly:'9,500,000',
			rentPricDaily:'null',
			availability:'in-stock',
			stockQuantity:3,
			coverGradient:'from-green-900 to-dark-950',
			sortOrder:9, isActive:1 }
	]).run();
}
